/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3" | "h2";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  endDate?: string;
  time?: string;
  location?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
  link?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  category: CategoryReference;
  price: number;
  colors?: Array<string>;
  sizes?: Array<string>;
  customFields?: Array<{
    label: string;
    kind: "select" | "text";
    options?: Array<string>;
    required?: boolean;
    _key: string;
  }>;
  extras?: Array<{
    name: string;
    price: number;
    _key: string;
  }>;
  description?: string;
  details?: RichText;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  personalizable?: boolean;
  withSymbols?: boolean;
  withNote?: boolean;
  withName?: boolean;
  onRequest?: boolean;
  digital?: boolean;
  available?: boolean;
  stock?: number;
  sortOrder?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  sortOrder?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  comingSoon?: boolean;
  comingSoonText?: string;
  previewPassword?: string;
  siteName?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroText?: string;
  highlights?: Array<{
    title: string;
    text?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    link?:
      | "/shop"
      | "/shop#personalisierung"
      | "/ueber-mich"
      | "/maerkte-events"
      | "/kontakt";
    _key: string;
  }>;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  values?: Array<string>;
  personalizationTitle?: string;
  personalizationText?: RichText;
  notePlaceholder?: string;
  namePlaceholder?: string;
  motifs?: Array<{
    name: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  aboutTitle?: string;
  aboutText?: RichText;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderInfo?: RichText;
  shippingInfo?: RichText;
  shippingOptions?: Array<{
    name: string;
    price: number;
    _key: string;
  }>;
  twintQr?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  giftWrapPrice?: number;
  freeShippingFrom?: number;
  faqs?: Array<{
    question: string;
    answer: RichText;
    _key: string;
  }>;
  ownerName?: string;
  address?: string;
  email?: string;
  instagram?: string;
  agbText?: RichText;
  privacyText?: RichText;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichText
  | SanityImageAssetReference
  | Event
  | SanityImageCrop
  | SanityImageHotspot
  | CategoryReference
  | Product
  | Category
  | Slug
  | ProductReference
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]
export type SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  comingSoon?: boolean;
  comingSoonText?: string;
  previewPassword?: string;
  siteName?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroTitle?: string;
  heroSubtitle?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroText?: string;
  highlights?: Array<{
    title: string;
    text?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    link?:
      | "/kontakt"
      | "/maerkte-events"
      | "/shop"
      | "/shop#personalisierung"
      | "/ueber-mich";
    _key: string;
  }>;
  featuredProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  values?: Array<string>;
  personalizationTitle?: string;
  personalizationText?: RichText;
  notePlaceholder?: string;
  namePlaceholder?: string;
  motifs?: Array<{
    name: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _key: string;
  }>;
  aboutTitle?: string;
  aboutText?: RichText;
  aboutImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderInfo?: RichText;
  shippingInfo?: RichText;
  shippingOptions?: Array<{
    name: string;
    price: number;
    _key: string;
  }>;
  twintQr?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  giftWrapPrice?: number;
  freeShippingFrom?: number;
  faqs?: Array<{
    question: string;
    answer: RichText;
    _key: string;
  }>;
  ownerName?: string;
  address?: string;
  email?: string;
  instagram?: string;
  agbText?: RichText;
  privacyText?: RichText;
} | null;

// Source: ../web/src/lib/sanity.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(sortOrder asc, title asc) {  _id, title, "slug": slug.current, description,  "products": *[_type == "product" && references(^._id) && defined(slug.current)]    | order(sortOrder asc, name asc) {      _id, name, "slug": slug.current, price, colors, sizes, extras, customFields, description, details, images,      "personalizable": coalesce(personalizable, false),      "withSymbols": coalesce(withSymbols, true),      "withNote": coalesce(withNote, true),      "withName": coalesce(withName, false),      // Bestand 0 → automatisch «Auf Anfrage»      "onRequest": coalesce(onRequest, false) || (defined(stock) && stock <= 0),      stock,      "digital": coalesce(digital, false),      "available": coalesce(available, true)    }}
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  products: Array<{
    _id: string;
    name: string;
    slug: string;
    price: number;
    colors: Array<string> | null;
    sizes: Array<string> | null;
    extras: Array<{
      name: string;
      price: number;
      _key: string;
    }> | null;
    customFields: Array<{
      label: string;
      kind: "select" | "text";
      options?: Array<string>;
      required?: boolean;
      _key: string;
    }> | null;
    description: string | null;
    details: RichText | null;
    images: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    personalizable: boolean | false;
    withSymbols: boolean | true;
    withNote: boolean | true;
    withName: boolean | false;
    onRequest: boolean | false | true | null;
    stock: number | null;
    digital: boolean | false;
    available: boolean | true;
  }>;
}>;

// Source: ../web/src/lib/sanity.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && coalesce(endDate, date) >= $today] | order(date asc) {  _id, title, date, endDate, time, location, description, link, image}
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  date: string;
  endDate: string | null;
  time: string | null;
  location: string | null;
  description: string | null;
  link: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]': SETTINGS_QUERY_RESULT;
    '*[_type == "category" && defined(slug.current)] | order(sortOrder asc, title asc) {\n  _id, title, "slug": slug.current, description,\n  "products": *[_type == "product" && references(^._id) && defined(slug.current)]\n    | order(sortOrder asc, name asc) {\n      _id, name, "slug": slug.current, price, colors, sizes, extras, customFields, description, details, images,\n      "personalizable": coalesce(personalizable, false),\n      "withSymbols": coalesce(withSymbols, true),\n      "withNote": coalesce(withNote, true),\n      "withName": coalesce(withName, false),\n      // Bestand 0 \u2192 automatisch \xABAuf Anfrage\xBB\n      "onRequest": coalesce(onRequest, false) || (defined(stock) && stock <= 0),\n      stock,\n      "digital": coalesce(digital, false),\n      "available": coalesce(available, true)\n    }\n}': CATEGORIES_QUERY_RESULT;
    '*[_type == "event" && coalesce(endDate, date) >= $today] | order(date asc) {\n  _id, title, date, endDate, time, location, description, link, image\n}': EVENTS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
